VERSION ?= $(shell tr -d '[:space:]' < VERSION)
CODESIGN_IDENTITY ?= Apple Development
EXPECTED_CODESIGN_AUTHORITY_PREFIX ?= Authority=Apple Development:
CODE_SIGN_STYLE ?= Manual
DEVELOPMENT_TEAM ?=
BUILD_NUMBER ?= 1
RELEASE_DIR ?= .release-native
RELEASE_TAG ?= v$(VERSION)
APP_INSTALL_DIR ?= /Applications
SPARKLE_PUBLIC_KEY ?=
ARGS ?=

.PHONY: generate xcodeproj build build-clean run run-clean cli check release install installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_BUILD_NUMBER="$(BUILD_NUMBER)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	export XCODEGEN_WINMUX_SPARKLE_PUBLIC_KEY="$(SPARKLE_PUBLIC_KEY)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux-native-cli .debug && \
	cp -r .build/debug/WinMuxApp .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux-native-cli $(ARGS)'

check:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	swift test && \
	python3 -m unittest script/test_validate_appcast.py && \
	python3 -m unittest script/test_fork_identity.py && \
	swift package resolve && \
	git diff --exit-code -- Package.resolved'

release:
	$(MAKE) native-build VERSION="$(VERSION)" BUILD_NUMBER="$(BUILD_NUMBER)"

install:
	@echo 'Install .release-native/WinMuxX-Native.app explicitly. This target never replaces WinMux.app.' >&2
	@exit 1
installed: install

.PHONY: native-build
native-build:
	VERSION="$(VERSION)" BUILD_NUMBER="$(BUILD_NUMBER)" bash script/native-build.sh

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
